services:
  traefik:
    environment:
      TRAEFIK_STATIC_CONFIG: ${TRAEFIK_PUBLIC_HTTP_CONFIG:-traefik-acme-staging.yml}
    ports: !override
      - name: public-http
        target: 80
        published: '80'
        host_ip: 0.0.0.0
        protocol: tcp
      - name: internal-https
        target: 443
        published: '18443'
        host_ip: 127.0.0.1
        protocol: tcp
