api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ':80'
    forwardedHeaders:
      insecure: false
  websecure:
    address: ':443'
    forwardedHeaders:
      insecure: false
    http:
      tls: {}

providers:
  file:
    directory: /run/traefik/dynamic
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json
