api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ':80'
    forwardedHeaders:
      insecure: false
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'
    forwardedHeaders:
      insecure: false
    http:
      tls:
        certResolver: letsencrypt

providers:
  file:
    directory: /run/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: __ACME_EMAIL__
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /var/lib/traefik/acme-staging.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  format: json

accessLog:
  format: json
