export enum AuthAuditEventType {
  REGISTRATION_SUCCEEDED = 'auth.registration.succeeded',
  EMAIL_VERIFIED = 'auth.email.verified',
  PASSWORD_RESET_SUCCEEDED = 'auth.password_reset.succeeded',
  OTP_ISSUED = 'auth.otp.issued',
  OTP_CONSUMED = 'auth.otp.consumed',
  OTP_REJECTED = 'auth.otp.rejected',
  OTP_DELIVERY_FAILED = 'auth.otp.delivery_failed',
  LOGIN_SUCCEEDED = 'auth.login.succeeded',
  LOGIN_FAILED = 'auth.login.failed',
  REFRESH_SUCCEEDED = 'auth.refresh.succeeded',
  REFRESH_FAILED = 'auth.refresh.failed',
  REFRESH_REUSE_DETECTED = 'auth.refresh.reuse_detected',
  LOGOUT = 'auth.logout',
  LOGOUT_ALL = 'auth.logout_all',
}
